Combining 2 files into 1

diff --git a/.github/workflows/test-dockerfile-devcontainer.yml b/.github/workflows/test-dockerfile-devcontainer.yml
--- a/.github/workflows/test-dockerfile-devcontainer.yml
+++ b/.github/workflows/test-dockerfile-devcontainer.yml
@@ -26,8 +26,11 @@ on:
 # #############################
 # jobs
 # #############################
+# #############################
+# job-dockerfile
+# #############################
 jobs:
-  validate-image:
+  job-dockerfile:
     runs-on: ubuntu-22.04
     steps:
       # ----------
@@ -82,4 +85,57 @@ jobs:
           else
             echo "❌ Error: The line '${{ env.ROS_SOURCE_STR }}' was not found in .bashrc."
             exit 1
+          fi
+
+    # #############################
+    # job-dockerfile
+    # #############################
+  job-devcontainer:
+    runs-on: ubuntu-22.04
+    steps:
+      # ----------
+      # Checkout
+      # ----------
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      # ----------
+      # Install DevContainer CLI for the tests
+      # ----------
+      - name: Install Dev Container CLI
+        run: npm install -g @devcontainers/cli
+
+      # ----------
+      # Build and make it alive
+      # ----------
+      - name: Build and Up Dev Container
+        run: |
+          devcontainer up --workspace-folder .
+
+      # ----------
+      # Test 1
+      # ----------
+      - name: Test 1 - Check Workspace Folder
+        run: |
+          RESULT=$(devcontainer exec --workspace-folder . pwd)
+          echo "Workspace is: [$RESULT]"
+          if [ "$RESULT" == "/workspaces" ]; then
+              echo "✅ Workspace OK."
+          else
+              echo "❌ Error: Expected /workspaces but got [$RESULT]."
+              exit 1
+          fi
+
+      # ----------
+      # Test 2
+      # ----------
+      - name: Test 2 - Check Remote User
+        run: |
+          RESULT=$(devcontainer exec --workspace-folder . whoami)
+          echo "Remote user is: [$RESULT]"
+          if [ "$RESULT" == "badprog" ]; then
+              echo "✅ User OK."
+          else
+              echo "❌ Error: Expected badprog but got [$RESULT]."
+              exit 1
           fi
